config/routes.rb
AddressBook::Application.routes.draw do

  resources :people

  root :to => 'people#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(params[:person])
    if @person.save
      redirect_to root_path, :notice => 'Person was successfully created.'
    else
      render :action => "new"
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update_attributes(params[:person])
      redirect_to root_path, :notice => 'Person was successfuly updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<container>
  <div class="row">
    <div class="span10 offset2">
      <p id="notice"><%= notice %></p>
    </div>
  </div>
  <div class="row">
    <div class="span10 offset2">
      <%= yield %>
    </div>
  </div>
</container>
</body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<section>
  <%= form_for(@person) do |f| %>
    <% if @person.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

        <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    
    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</section>

app/views/people/index.html.erb
<section>
  <h1>Addresses</h1>
</section>
<section id="address_table">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%- @people.each do |person| %>
        <tr>
          <td><%= person.last_name %></td>
          <td><%= person.first_name %></td>
          <td><%= person.email %></td>
          <td><%= person.phone %></td>
          <td>
            <%= link_to 'View', person_path(person) %> | 
            <%= link_to 'Edit', edit_person_path(person) %> |
            <%= link_to 'Delete', person, :method => :delete, :data => { :confirm => "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>
<br />
<%= link_to "New Person", new_person_path, :class => 'btn' %>

app/views/people/new.html.erb
<h1>New Person</h1>
<section>
  <%= form_for(@person) do |f| %>
    <% if @person.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

        <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    
    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</section>

app/views/people/show.html.erb
<section>
  <h2><%= "#{@person.first_name} #{@person.last_name}" %></h2>
  
  <p>
    <b>Email: </b>
    <%= @person.email %>
  </p>

  <p>
    <b>Phone: </b>
    <%= @person.phone %>
  </p>

</section>